sudo: required

language: c

cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/vrom911/Compiler/.stack-work"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - llvm-3.5
      - llvm-3.5-dev
      - g++-4.8
      - libgmp-dev

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --version
  - stack -j 2 setup --no-terminal
  - stack ghc -- --version
  - stack -j 2 build --test --only-snapshot --no-terminal

script:
  - stack --jobs=4 build --test --no-terminal
